name = "dracinfree"
compatibility_date = "2024-04-05"

[assets]
directory = "."

# Konfigurasi Database Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "melolo-db"
database_id = "f5b3cc88-abff-4c5c-8fcf-d9f2c1ae9615"
